version: '2'
services:
  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
    ports:
      - 3000:3000
    network_mode: "host"

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    network_mode: "host"
    volumes:
      - ./prometheus-data:/prometheus-data
    command: -config.file=/prometheus-data/prometheus.yml

#  hello1:
#    build: ./hello1
#    network_mode: "host"
#
#  hello2:
#    build: ./hello2
#    network_mode: "host"
