global:
  scrape_interval:     15s
  evaluation_interval: 30s

scrape_configs:

  - job_name: 'hello1'

    scrape_interval: 5s
    scrape_timeout: 10s
    metrics_path: '/prometheus'

    target_groups:
     - targets: ['localhost:8000']